# Generated by Django 4.2.7 on 2023-12-15 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='posted_by',
        ),
    ]
